/**
 * Voice transcript classifier.
 *
 * Two-tier approach:
 *   1. Quick heuristic pre-filter (no subprocess)
 *   2. Claude CLI call with --model haiku for AI classification,
 *      conversation summary, and application routing.
 *
 * No API keys needed — uses the already-authenticated `claude` CLI.
 * The classifier is pluggable so tests can stub it.
 */

import { execFile } from 'node:child_process';
import { db, schema } from '../db/index.js';

export interface VoiceClassificationInput {
  /** Concatenated transcript text for the window being classified. */
  text: string;
  /** Previous window's text, if any, for short context. */
  previousText?: string;
  /** Summary of the conversation so far (generated by summarizer). */
  conversationSummary?: string;
  /** App context the user is working against. */
  appId?: string | null;
  sourceUrl?: string | null;
}

export interface VoiceClassificationResult {
  actionable: boolean;
  /** Short imperative title suitable for a feedback item. */
  title: string;
  /** Longer description, typically echoing the ask in the user's words. */
  description: string;
  /** Why the classifier decided this. Shown in logs / debug. */
  reason: string;
  /** Optional tags to attach beyond the default voice-captured tag. */
  tags?: string[];
  /** If multi-app, the app ID this brainstorm chunk should route to. */
  routedAppId?: string;
  /** Human-readable app name for display. */
  appName?: string;
}

export type VoiceClassifier = (
  input: VoiceClassificationInput
) => Promise<VoiceClassificationResult>;

const CLAUDE_BIN = process.env.CLAUDE_BIN || 'claude';
const CLASSIFIER_MODEL = process.env.VOICE_CLASSIFIER_MODEL || 'claude-haiku-4-5-20251001';

const ACTION_VERBS = [
  'add', 'build', 'fix', 'change', 'update', 'remove', 'rename',
  'make', 'create', 'refactor', 'let me', 'can you', 'we should',
  'please', 'need to', 'should be able', 'i want', 'wire up',
  'show', 'hide', 'implement',
];

const NON_ACTION_MARKERS = [
  'i think', 'maybe', 'hmm', 'um', 'huh',
];

function heuristicClassifier(
  input: VoiceClassificationInput
): VoiceClassificationResult {
  const trimmed = input.text.trim();
  if (trimmed.length < 30) {
    return { actionable: false, title: '', description: trimmed, reason: 'too-short' };
  }

  const lower = trimmed.toLowerCase();
  const hasVerb = ACTION_VERBS.some((v) => lower.includes(v));
  const hasNonActionOnly = !hasVerb &&
    NON_ACTION_MARKERS.some((m) => lower.startsWith(m));

  if (!hasVerb || hasNonActionOnly) {
    return {
      actionable: false, title: '', description: trimmed,
      reason: hasVerb ? 'hedged' : 'no-action-verb',
    };
  }

  const firstSentence = trimmed.split(/[.!?]\s+/)[0] || trimmed;
  const title = (firstSentence.length > 80
    ? firstSentence.slice(0, 77) + '...'
    : firstSentence).replace(/^(can you|please|let me|i want to?|we should)\s+/i, '');

  return {
    actionable: true,
    title: title.charAt(0).toUpperCase() + title.slice(1),
    description: trimmed,
    reason: 'heuristic-action-verb',
  };
}

/** Run `claude -p <prompt> --model <model> --output-format json` and return parsed output. */
function runClaude(prompt: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const child = execFile(
      CLAUDE_BIN,
      ['-p', prompt, '--model', CLASSIFIER_MODEL, '--output-format', 'json'],
      { timeout: 30_000, maxBuffer: 1024 * 256 },
      (err, stdout, stderr) => {
        if (err) return reject(err);
        resolve(stdout);
      },
    );
  });
}

/** Extract JSON from claude CLI output (may have markdown fences or wrapper). */
function extractJson(raw: string): any {
  // The --output-format json wraps in {"type":"result","result":"..."}
  try {
    const wrapper = JSON.parse(raw);
    if (wrapper?.result) {
      // result is the text content — may contain JSON
      const inner = wrapper.result;
      // Try parsing the inner content directly
      try { return JSON.parse(inner); } catch {}
      // Try extracting from markdown code fences
      const fenced = inner.match(/```(?:json)?\s*([\s\S]*?)```/);
      if (fenced) return JSON.parse(fenced[1].trim());
      // Try finding a JSON object in the text
      const braceMatch = inner.match(/\{[\s\S]*\}/);
      if (braceMatch) return JSON.parse(braceMatch[0]);
    }
  } catch {}
  // Fallback: try raw as JSON
  try { return JSON.parse(raw); } catch {}
  const fenced = raw.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fenced) return JSON.parse(fenced[1].trim());
  const braceMatch = raw.match(/\{[\s\S]*\}/);
  if (braceMatch) return JSON.parse(braceMatch[0]);
  throw new Error('Could not parse JSON from claude output');
}

function getAppList(): { id: string; name: string; description: string | null }[] {
  return db
    .select({
      id: schema.applications.id,
      name: schema.applications.name,
      description: schema.applications.description,
    })
    .from(schema.applications)
    .all();
}

async function aiClassifier(
  input: VoiceClassificationInput
): Promise<VoiceClassificationResult> {
  const trimmed = input.text.trim();
  if (trimmed.length < 20) {
    return { actionable: false, title: '', description: trimmed, reason: 'too-short' };
  }

  const apps = getAppList();
  const appListText = apps.length > 0
    ? apps.map((a) => `- ${a.id}: ${a.name}${a.description ? ` (${a.description})` : ''}`).join('\n')
    : '(no applications registered)';

  const currentApp = input.appId
    ? apps.find((a) => a.id === input.appId)
    : null;

  const prompt = `You are a brainstorm transcript classifier for a development feedback system.
Given a chunk of speech transcript from a brainstorming session, determine:
1. Is this actionable? (contains a concrete request, idea, or task for a developer)
2. If actionable, extract a clear title and description
3. If there are multiple applications, route to the most relevant one

Available applications:
${appListText}

${currentApp ? `The user is currently on: ${currentApp.name} (${currentApp.id})` : ''}

${input.conversationSummary ? `Conversation context so far:\n${input.conversationSummary}\n` : ''}
${input.previousText ? `Previous chunk:\n${input.previousText}\n` : ''}
Current transcript chunk:
${trimmed}

Respond with valid JSON only (no markdown fences), with these fields:
{
  "actionable": boolean,
  "title": "imperative title if actionable",
  "description": "clear description of what to do",
  "reason": "why you classified it this way",
  "tags": ["optional", "tags"],
  "routedAppId": "app ID to route to, or null",
  "appName": "human-readable app name, or null"
}`;

  try {
    const raw = await runClaude(prompt);
    const parsed = extractJson(raw);
    return {
      actionable: !!parsed.actionable,
      title: parsed.title || '',
      description: parsed.description || trimmed,
      reason: parsed.reason || 'ai-classifier',
      tags: parsed.tags,
      routedAppId: parsed.routedAppId || undefined,
      appName: parsed.appName || undefined,
    };
  } catch (err) {
    console.warn('[voice-classifier] AI classification failed, falling back to heuristic:', err);
    return heuristicClassifier(input);
  }
}

/** Summarize previous conversation chunks to provide context. */
export async function summarizeConversation(
  chunks: string[]
): Promise<string | undefined> {
  if (chunks.length === 0) return undefined;

  const prompt = `Summarize this brainstorming conversation in 2-3 sentences. Focus on the key ideas and any decisions made. Be concise. Output only the summary, no preamble.

${chunks.join('\n\n')}`;

  try {
    const raw = await runClaude(prompt);
    // Extract just the text result
    try {
      const wrapper = JSON.parse(raw);
      if (wrapper?.result) return wrapper.result.trim();
    } catch {}
    return raw.trim();
  } catch {
    return chunks.slice(-3).join(' ').slice(0, 300);
  }
}

let currentClassifier: VoiceClassifier = aiClassifier;

export function setVoiceClassifier(fn: VoiceClassifier): void {
  currentClassifier = fn;
}

export function resetVoiceClassifier(): void {
  currentClassifier = aiClassifier;
}

export async function classifyVoiceWindow(
  input: VoiceClassificationInput
): Promise<VoiceClassificationResult> {
  return currentClassifier(input);
}
