import { Hono } from 'hono';
import { feedbackRoutes } from './feedback.js';
import { agentRoutes } from './agents.js';
import { systemRoutes } from './system.js';
import { notificationRoutes } from './notifications.js';
import { chiefOfStaffRoutes } from './chief-of-staff.js';
import { cosLearningsRoutes } from './cos-learnings.js';
import { cosChannelRoutes } from './cos-channels.js';
import { cosChannelOrganizeRoutes } from './cos-channel-organize.js';
import { cosApprovalRoutes } from './cos-approvals.js';
import { sessionFollowupRoutes } from './session-followups.js';
import { composerDraftsRoutes } from './composer-drafts.js';
import { flatterRoutes } from './flatter.js';
import { userRoutes } from './users.js';

export const adminRoutes = new Hono();

adminRoutes.route('/', userRoutes);
adminRoutes.route('/', feedbackRoutes);
adminRoutes.route('/', agentRoutes);
adminRoutes.route('/', systemRoutes);
adminRoutes.route('/', notificationRoutes);
adminRoutes.route('/', chiefOfStaffRoutes);
adminRoutes.route('/', cosLearningsRoutes);
adminRoutes.route('/', cosChannelRoutes);
adminRoutes.route('/', cosChannelOrganizeRoutes);
adminRoutes.route('/', cosApprovalRoutes);
adminRoutes.route('/', sessionFollowupRoutes);
adminRoutes.route('/', composerDraftsRoutes);
adminRoutes.route('/', flatterRoutes);
